### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by harshchoudhary272**

### CODE REVIEW

**Comment by Uyadav207** [comment]
@harshchoudhary272 

**Do not Spam the PR Section**

I am Right Now closing this PR. As the changes you are making is `unnecessary`.

If you want to Contribute `Do participate with your team`. and register as told.

Regard,
Utkarsh
GitHub Moderator [CODE CAMP]
@ISTESRMNCR

**Comment by harshchoudhary272** [comment]
I don't have any team and I want to participate on my own

**Comment by Uyadav207** [comment]
@harshchoudhary272 ,Yes! You can participate Solo

**Comment by harshchoudhary272** [comment]
Please tell me the steps

**Comment by Uyadav207** [comment]
Check it out Here : https://codecamphackathon.netlify.app/

The pull request will be merged from `19th July, 2020`....

Themes will be  displayed on `15th JULY, 2020`... on social media platform . as well as on website.

**Comment by harshchoudhary272** [comment]
How do I contribute ?

**Comment by Uyadav207** [comment]
@harshchoudhary272 , Nothing to contribute for Now.   
Only contribute as a Participant.. Do participate in the Hackathon. That would be a great contribution.

Everything is on website. Kindly Just go through it...

`These PR session has been closed. So messages here will not be Replied.`

**Pull request closed without merging**
